'use client'
import { useThemeStore } from '@/store/theme'

const sections = [
  {
    title: '1. Acceptance of Terms',
    body: 'By accessing or using Orchestra MCP ("Orchestra", "the Service"), you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this website are protected by applicable copyright and trademark law.',
  },
  {
    title: '2. Use License',
    body: 'Permission is granted to temporarily use Orchestra for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title. Under this license you may not: modify or copy the materials; use the materials for any commercial purpose or for any public display; attempt to decompile or reverse engineer any software contained in Orchestra; remove any copyright or other proprietary notations from the materials; or transfer the materials to another person or mirror the materials on any other server.',
  },
  {
    title: '3. Account Terms',
    body: 'You are responsible for maintaining the security of your account and password. Orchestra cannot and will not be liable for any loss or damage from your failure to comply with this security obligation. You are responsible for all content posted and activity that occurs under your account. You must not use the Service to violate any laws in your jurisdiction.',
  },
  {
    title: '4. Service Availability',
    body: 'Orchestra does not warrant that the Service will be uninterrupted, timely, secure, or error-free. We reserve the right to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. You agree that Orchestra shall not be liable to you or any third party for any modification, suspension, or discontinuance of the Service.',
  },
  {
    title: '5. AI and Generated Content',
    body: 'Orchestra provides tools that interface with AI language models. The outputs generated by AI models through Orchestra are not endorsed by Orchestra. You are solely responsible for how you use AI-generated content. Orchestra is not liable for any decisions made based on AI outputs. You agree to comply with the terms of service of any AI provider you connect through Orchestra.',
  },
  {
    title: '6. Data and Privacy',
    body: 'Your use of the Service is also governed by our Privacy Policy. By using the Service, you agree to the collection and use of information in accordance with our Privacy Policy. You retain all rights to data you upload to the Service. We do not sell your personal data to third parties.',
  },
  {
    title: '7. API Usage',
    body: 'Access to the Orchestra API is subject to rate limiting and fair use policies. Automated access to the Service must comply with our API documentation. We reserve the right to suspend or terminate API access for abuse, excessive usage, or violation of these terms.',
  },
  {
    title: '8. Limitations',
    body: 'In no event shall Orchestra or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use Orchestra. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.',
  },
  {
    title: '9. Governing Law',
    body: 'These terms and conditions are governed by and construed in accordance with applicable law and you irrevocably submit to the exclusive jurisdiction of the courts in that location. Any dispute arising in connection with these Terms shall be resolved by binding arbitration.',
  },
  {
    title: '10. Changes to Terms',
    body: 'Orchestra reserves the right to modify these terms at any time. We will notify users of material changes via email or by posting a notice on the Service. Your continued use of the Service after any changes to these Terms constitutes your acceptance of the new Terms of Service.',
  },
]

export default function TermsPage() {
  const { theme } = useThemeStore()
  const isDark = theme === 'dark'
  const textPrimary = isDark ? '#f8f8f8' : '#0f0f12'
  const textMuted = isDark ? 'rgba(255,255,255,0.35)' : 'rgba(0,0,0,0.4)'
  const textBody = isDark ? 'rgba(255,255,255,0.55)' : 'rgba(0,0,0,0.6)'
  const introBg = isDark ? 'rgba(255,255,255,0.03)' : '#ffffff'
  const introBorder = isDark ? 'rgba(255,255,255,0.07)' : 'rgba(0,0,0,0.08)'
  const dividerColor = isDark ? 'rgba(255,255,255,0.07)' : 'rgba(0,0,0,0.08)'

  return (
    <div style={{ maxWidth: 720, margin: '0 auto', padding: '72px 32px' }}>
      <div style={{ marginBottom: 48 }}>
        <h1 style={{ fontSize: 'clamp(28px, 4vw, 44px)', fontWeight: 800, letterSpacing: '-0.04em', color: textPrimary, marginBottom: 12 }}>Terms of Service</h1>
        <p style={{ fontSize: 14, color: textMuted }}>Last updated: February 28, 2026</p>
      </div>

      <div style={{ fontSize: 15, color: textBody, lineHeight: 1.75, marginBottom: 40, padding: '20px', borderRadius: 10, background: introBg, border: `1px solid ${introBorder}` }}>
        Please read these Terms of Service carefully before using Orchestra. These terms govern your access to and use of Orchestra MCP and its services.
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 36 }}>
        {sections.map(s => (
          <div key={s.title}>
            <h2 style={{ fontSize: 18, fontWeight: 700, color: textPrimary, marginBottom: 12, letterSpacing: '-0.02em' }}>{s.title}</h2>
            <p style={{ fontSize: 15, color: textBody, lineHeight: 1.75, margin: 0 }}>{s.body}</p>
          </div>
        ))}
      </div>

      <div style={{ marginTop: 56, paddingTop: 32, borderTop: `1px solid ${dividerColor}`, fontSize: 14, color: textMuted }}>
        Questions about these terms? <a href="mailto:legal@orchestra-mcp.dev" style={{ color: '#00e5ff', textDecoration: 'none' }}>legal@orchestra-mcp.dev</a>
      </div>
    </div>
  )
}
