/**
 * Generate PNG icon data from Boxicons SVGs.
 *
 * Usage: node scripts/generate-icons.mjs
 *
 * Reads Boxicons SVGs, renders them at 16x16 using @resvg/resvg-js,
 * and outputs a TypeScript file with base64-encoded PNG data.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Resvg } from '@resvg/resvg-js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const BOXICONS_DIR = join(ROOT, 'node_modules/boxicons/svg/regular');

// Map our icon names to Boxicons filenames
const ICON_MAP = {
  music: 'bx-music',
  message: 'bx-message-rounded',
  book: 'bx-book-open',
  info: 'bx-info-circle',
  refresh: 'bx-refresh',
  settings: 'bx-cog',
  power: 'bx-power-off',
  globe: 'bx-globe',
  server: 'bx-server',
  play: 'bx-play',
  pause: 'bx-pause',
  stop: 'bx-stop',
  bell: 'bx-bell',
  'bell-off': 'bx-bell-off',
  volume: 'bx-volume-full',
  'volume-mute': 'bx-volume-mute',
  search: 'bx-search',
  coffee: 'bx-coffee',
  calendar: 'bx-calendar',
  video: 'bx-video',
  alarm: 'bx-alarm',
  timer: 'bx-timer',
  time: 'bx-time',
  task: 'bx-task',
  link: 'bx-link',
  list: 'bx-list-ul',
  grid: 'bx-grid-alt',
  check: 'bx-check',
};

// Colored icon variants: "outputName" → { icon, color }
const COLORED_VARIANTS = {
  // Service status icons (globe for Browser Connection, server for MCP Server)
  'globe-green': { icon: 'bx-globe', color: '#34C759' },
  'globe-yellow': { icon: 'bx-globe', color: '#FF9500' },
  'globe-red': { icon: 'bx-globe', color: '#FF3B30' },
  'server-green': { icon: 'bx-server', color: '#34C759' },
  'server-yellow': { icon: 'bx-server', color: '#FF9500' },
  'server-red': { icon: 'bx-server', color: '#FF3B30' },
  // Submenu action icons
  'play-green': { icon: 'bx-play', color: '#34C759' },
  'stop-red': { icon: 'bx-stop', color: '#FF3B30' },
  'refresh-orange': { icon: 'bx-refresh', color: '#FF9500' },
  'bell-blue': { icon: 'bx-bell', color: '#007AFF' },
  'volume-blue': { icon: 'bx-volume-full', color: '#007AFF' },
  // Secondary tray timer icons
  'timer-green': { icon: 'bx-timer', color: '#34C759' },
  'timer-yellow': { icon: 'bx-timer', color: '#FF9500' },
  'timer-red': { icon: 'bx-timer', color: '#FF3B30' },
};

const SIZE = 16;
const entries = [];

/**
 * Render a Boxicons SVG to base64 PNG.
 */
function renderIcon(bxName, fillColor = '#000000') {
  const svgPath = join(BOXICONS_DIR, `${bxName}.svg`);
  let svg = readFileSync(svgPath, 'utf-8');

  // Set fill color (Boxicons uses no fill or currentColor)
  svg = svg.replace(/fill="currentColor"/g, `fill="${fillColor}"`);
  // Also inject fill on the path elements that have no fill attribute
  svg = svg.replace(/<path d=/g, `<path fill="${fillColor}" d=`);

  svg = svg
    .replace(/width="\d+"/, `width="${SIZE}"`)
    .replace(/height="\d+"/, `height="${SIZE}"`);

  const resvg = new Resvg(svg, {
    fitTo: { mode: 'width', value: SIZE },
    background: 'rgba(0, 0, 0, 0)',
  });

  const rendered = resvg.render();
  return rendered.asPng();
}

// Generate monochrome (template) icons
console.log('Monochrome icons:');
for (const [name, bxName] of Object.entries(ICON_MAP)) {
  const pngBuffer = renderIcon(bxName);
  const base64 = Buffer.from(pngBuffer).toString('base64');
  entries.push({ name, base64 });
  console.log(`  ${name}: ${pngBuffer.length} bytes`);
}

// Generate colored variants
console.log('\nColored icons:');
for (const [name, { icon, color }] of Object.entries(COLORED_VARIANTS)) {
  const pngBuffer = renderIcon(icon, color);
  const base64 = Buffer.from(pngBuffer).toString('base64');
  entries.push({ name, base64 });
  console.log(`  ${name}: ${pngBuffer.length} bytes (${color})`);
}

// Generate TypeScript file
const output = `/**
 * Auto-generated Boxicons PNG data.
 * Generated by: node scripts/generate-icons.mjs
 *
 * DO NOT EDIT — regenerate with the script above.
 * Icons from Boxicons (https://boxicons.com), MIT License.
 */

/** Base64-encoded 16x16 PNG icon data, keyed by icon name. */
export const ICON_DATA: Record<string, string> = {
${entries.map(({ name, base64 }) => `  '${name}': '${base64}',`).join('\n')}
};

/**
 * Colored icon names — these should NOT be set as template images
 * because they have intentional colors.
 */
export const COLORED_ICONS: Set<string> = new Set([
${Object.keys(COLORED_VARIANTS).map((n) => `  '${n}',`).join('\n')}
]);
`;

const outPath = join(ROOT, 'src/icon-data.ts');
writeFileSync(outPath, output, 'utf-8');
console.log(`\nGenerated: ${outPath}`);
console.log(`Total icons: ${entries.length}`);
